# Generated by Django 5.2.17 on 2026-08-24 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("organization", models.CharField(max_length=160)),
                (
                    "issue_date",
                    models.CharField(
                        help_text='e.g. "Jan 2025" or "2025"', max_length=40
                    ),
                ),
                ("credential_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=160)),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurrentlyLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=220)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Currently learning",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=160)),
                ("degree", models.CharField(max_length=160)),
                ("field", models.CharField(blank=True, max_length=160)),
                ("start_year", models.PositiveIntegerField()),
                ("end_year", models.PositiveIntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=60)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-start_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "timeframe",
                    models.CharField(
                        help_text='e.g. "Mar 2025" or "Jun – Jul 2025"', max_length=60
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="One responsibility/contribution per line."
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True, help_text="Comma-separated.", max_length=300
                    ),
                ),
                ("company_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "headline",
                    models.CharField(
                        help_text="e.g. Python Developer | Junior AI Engineer",
                        max_length=160,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="One-line statement of what you build, shown in the hero.",
                        max_length=220,
                    ),
                ),
                ("summary", models.TextField(help_text="About-section narrative.")),
                (
                    "looking_for",
                    models.CharField(
                        blank=True,
                        help_text="Type of role/opportunity you're seeking.",
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                (
                    "timeframe",
                    models.CharField(
                        blank=True, help_text='e.g. "Feb 2026"', max_length=60
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="One or two sentences, shown on the project card.",
                        max_length=220,
                    ),
                ),
                ("problem_statement", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                (
                    "architecture_notes",
                    models.TextField(
                        blank=True,
                        help_text="One pipeline stage per line, e.g. 'Frontend → Django → ...'.",
                    ),
                ),
                ("challenges", models.TextField(blank=True)),
                ("future_improvements", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(help_text="Comma-separated.", max_length=400),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("fullstack", "Full Stack"),
                            ("web", "Web"),
                            ("ml", "Machine Learning"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai_ml", "AI / ML"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("database", "Database"),
                            ("cloud", "Cloud & Deploy"),
                            ("tools", "Tools"),
                            ("soft", "Soft Skills"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional short glyph/initials shown on the skill chip.",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("twitter", "X / Twitter"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=60)),
                (
                    "url",
                    models.CharField(
                        help_text="Full URL, or mailto:/tel: for email and phone.",
                        max_length=300,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/screenshots/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
