# Generated by Django 5.2.17 on 2026-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Shown in the About section. Optional — the section adapts if left blank.",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
