# Generated by Django 5.2.17 on 2026-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="illustration",
            field=models.ImageField(
                blank=True,
                help_text="Stylised/illustrated character art, shown centered in the hero. Optional — the hero falls back to the AI particle visual alone.",
                null=True,
                upload_to="profile/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot, shown in the About section. Optional.",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
