# Generated by Django 5.2.17 on 2026-08-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_illustration_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Separate image shown only in the homepage hero's floating side cards — independent of the main project image above. Falls back to a plain category label if left blank.",
                null=True,
                upload_to="projects/hero/",
            ),
        ),
    ]
