# Generated by Django 5.2.17 on 2026-08-28 08:45

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_hero_background_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hero_background_video",
            field=models.FileField(
                blank=True,
                help_text="Looping background video shown full-bleed beneath the hero headline. Optional — keep it short (a few seconds), silent, and heavily compressed (a few MB at most) since it autoplays muted and loops on every visit. Hidden entirely under prefers-reduced-motion.",
                null=True,
                storage=core.models._hero_video_storage,
                upload_to="profile/video/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov"]
                    )
                ],
            ),
        ),
    ]
